### ISSUE TITLE
Toluapp: Fails to build on OSX 10.8.4

### ISSUE THREAD

**Issue by bradc6** [LuaDist/Repository#149]
Toluapp fails to build on OSX 10.8.4 with the following errors.

toluapp/src/lib/tolua_map.c:414:19: Use of undeclared identifier 'LUA_GLOBALSINDEX'

toluapp/src/lib/tolua_map.c:448:19: Use of undeclared identifier 'LUA_GLOBALSINDEX'

Thank You
